########################################################################
#
# A class to handle language codes
#
########################################################################
from pprint import pprint

class LanguageCodes:
   
    #
    # Constructor
    # 
    def __init__(self):
        self.codes = self.__set_codes()

   
    #
    # Get html options for the selected language
    #
    def get_language_options_html(self, currentLang, languages):
        options = ""
        for lang, overrides in languages.items():
            options = options + '<option value="' + lang + '"'
            if currentLang == lang:
                options = options + ' selected={true}'
            options = options + ' >'
            options = options + self.codes[lang] 
            options = options + '</option>'
        return options 

    #
    # Get all language codes
    #
    def __set_codes(self):
        return  {
                "ar_AE" : "Arabic (United Arab Emirates)",
                "ar_BH" : "Arabic (Bahrain)",
                "ar_DJ" : "Arabic (Djibouti)",
                "ar_DZ" : "Arabic (Algeria)",
                "ar_EG" : "Arabic (Egypt)",
                "ar_EH" : "Arabic (Western Sahara)",
                "ar_ER" : "Arabic (Eritrea)",
                "ar_IL" : "Arabic (Israel)",
                "ar_IQ" : "Arabic (Iraq)",
                "ar_IQ" : "Arabic (Iraq)",
                "ar_JO" : "Arabic (Jordan)",
                "ar_JO" : "Arabic (Jordan)",
                "ar_KM" : "Arabic (Comoros)",
                "ar_KW" : "Arabic (Kuwait)",
                "ar_LB" : "Arabic (Lebanon)",
                "ar_LY" : "Arabic (Libya)",
                "ar_MA" : "Arabic (Morocco)",
                "ar_MR" : "Arabic (Mauritania)",
                "ar_OM" : "Arabic (Oman)",
                "ar_PS" : "Arabic (Palestinian Territories)",
                "ar_QA" : "Arabic (Qatar)",
                "ar_SA" : "Arabic (Saudi Arabia)",
                "ar_SD" : "Arabic (Sudan)",
                "ar_SO" : "Arabic (Somalia)",
                "ar_SS" : "Arabic (South Sudan)",
                "ar_SY" : "Arabic (Syria)",
                "ar_TD" : "Arabic (Chad)",
                "ar_TN" : "Arabic (Tunisia)",
                "ar_YE" : "Arabic (Yemen)",
                "as_IN" : "Assamese (India)",
                "asa_TZ" : "Asu (Tanzania)",
                "az_Cyrl" : "Azerbaijani (Cyrillic)",
                "az_Latn" : "Azerbaijani (Latin)",
                "bas_CM" : "Basaa (Cameroon)",
                "be_BY" : "Belarusian (Belarus)",
                "bem_ZM" : "Bemba (Zambia)",
                "bez_TZ" : "Bena (Tanzania)",
                "bg_BG" : "Bulgarian (Bulgaria)",
                "bm_ML" : "Bambara (Mali)",
                "bn_BD" : "Bengali (Bangladesh)",
                "bn_BD" : "Bangla (Bangladesh)",
                "bn_IN" : "Bengali (India)",
                "bn_IN" : "Bangla (India)",
                "bo_CN" : "Tibetan (China)",
                "bo_IN" : "Tibetan (India)",
                "br_FR" : "Breton (France)",
                "brx_IN" : "Bodo (India)",
                "bs_Cyrl" : "Bosnian (Cyrillic)",
                "bs_Latn" : "Bosnian (Latin)",
                "ca_AD" : "Catalan (Andorra)",
                "ca_ES" : "Catalan (Spain)",
                "ca_FR" : "Catalan (France)",
                "ca_IT" : "Catalan (Italy)",
                "ce_RU" : "Chechen (Russia)",
                "cgg_UG" : "Chiga (Uganda)",
                "chr_US" : "Cherokee (United States)",
                "cs_CZ" : "Czech (Czech Republic)",
                "cy_GB" : "Welsh (United Kingdom)",
                "da_DK" : "Danish (Denmark)",
                "dav_KE" : "Taita (Kenya)",
                "de_AT" : "German (Austria)",
                "de_BE" : "German (Belgium)",
                "de_CH" : "German (Switzerland)",
                "de_DE" : "German (Germany)",
                "de_IT" : "German (Italy)",
                "de_LI" : "German (Liechtenstein)",
                "de_LU" : "German (Luxembourg)",
                "de_LU" : "German (Luxembourg)",
                "dje_NE" : "Zarma (Niger)",
                "dsb_DE" : "Lower Sorbian (Germany)",
                "dua_CM" : "Duala (Cameroon)",
                "dyo_SN" : "Jola-Fonyi (Senegal)",
                "dz_BT" : "Dzongkha (Bhutan)",
                "ebu_KE" : "Embu (Kenya)",
                "ee_GH" : "Ewe (Ghana)",
                "ee_TG" : "Ewe (Togo)",
                "el_CY" : "Greek (Cyprus)",
                "el_GR" : "Greek (Greece)",
                "en_AG" : "English (Antigua & Barbuda)",
                "en_AI" : "English (Anguilla)",
                "en_AI" : "English (Anguilla)",
                "en_AS" : "English (American Samoa)",
                "en_AT" : "English (Austria)",
                "en_AU" : "English (Australia)",
                "en_AU" : "English (Australia)",
                "en_BB" : "English (Barbados)",
                "en_BE" : "English (Belgium)",
                "en_BI" : "English (Burundi)",
                "en_BM" : "English (Bermuda)",
                "en_BS" : "English (Bahamas)",
                "en_BW" : "English (Botswana)",
                "en_BZ" : "English (Belize)",
                "en_CA" : "English (Canada)",
                "en_CA" : "English (Canada)",
                "en_CC" : "English (Cocos [Keeling] Islands)",
                "en_CH" : "English (Switzerland)",
                "en_CK" : "English (Cook Islands)",
                "en_CM" : "English (Cameroon)",
                "en_CX" : "English (Christmas Island)",
                "en_CY" : "English (Cyprus)",
                "en_DE" : "English (Germany)",
                "en_DG" : "English (Diego Garcia)",
                "en_DK" : "English (Denmark)",
                "en_DM" : "English (Dominica)",
                "en_ER" : "English (Eritrea)",
                "en_FI" : "English (Finland)",
                "en_FJ" : "English (Fiji)",
                "en_FK" : "English (Falkland Islands)",
                "en_FM" : "English (Micronesia)",
                "en_GB" : "English (United Kingdom)",
                "en_GB" : "English (United Kingdom)",
                "en_GD" : "English (Grenada)",
                "en_GG" : "English (Guernsey)",
                "en_GH" : "English (Ghana)",
                "en_GI" : "English (Gibraltar)",
                "en_GM" : "English (Gambia)",
                "en_GU" : "English (Guam)",
                "en_GY" : "English (Guyana)",
                "en_HK" : "English (Hong Kong SAR China)",
                "en_IE" : "English (Ireland)",
                "en_IE" : "English (Ireland)",
                "en_IL" : "English (Israel)",
                "en_IM" : "English (Isle of Man)",
                "en_IN" : "English (India)",
                "en_IN" : "English (India)",
                "en_IO" : "English (British Indian Ocean Territory)",
                "en_JE" : "English (Jersey)",
                "en_JM" : "English (Jamaica)",
                "en_KE" : "English (Kenya)",
                "en_KI" : "English (Kiribati)",
                "en_KN" : "English (St. Kitts & Nevis)",
                "en_KY" : "English (Cayman Islands)",
                "en_LC" : "English (St. Lucia)",
                "en_LR" : "English (Liberia)",
                "en_LS" : "English (Lesotho)",
                "en_MG" : "English (Madagascar)",
                "en_MH" : "English (Marshall Islands)",
                "en_MO" : "English (Macau SAR China)",
                "en_MP" : "English (Northern Mariana Islands)",
                "en_MS" : "English (Montserrat)",
                "en_MT" : "English (Malta)",
                "en_MT" : "English (Malta)",
                "en_MU" : "English (Mauritius)",
                "en_MW" : "English (Malawi)",
                "en_MY" : "English (Malaysia)",
                "ne_NP" : "Nepali (Nepal)",
                "en_NA" : "English (Namibia)",
                "en_NF" : "English (Norfolk Island)",
                "en_NG" : "English (Nigeria)",
                "en_NL" : "English (Netherlands)",
                "en_NR" : "English (Nauru)",
                "en_NU" : "English (Niue)",
                "en_NZ" : "English (New Zealand)",
                "en_NZ" : "English (New Zealand)",
                "en_PG" : "English (Papua New Guinea)",
                "en_PH" : "English (Philippines)",
                "en_PH" : "English (Philippines)",
                "en_PK" : "English (Pakistan)",
                "en_PN" : "English (Pitcairn Islands)",
                "en_PR" : "English (Puerto Rico)",
                "en_PW" : "English (Palau)",
                "en_RW" : "English (Rwanda)",
                "en_SB" : "English (Solomon Islands)",
                "en_SC" : "English (Seychelles)",
                "en_SD" : "English (Sudan)",
                "en_SE" : "English (Sweden)",
                "en_SG" : "English (Singapore)",
                "en_SG" : "English (Singapore)",
                "en_SH" : "English (St. Helena)",
                "en_SI" : "English (Slovenia)",
                "en_SL" : "English (Sierra Leone)",
                "en_SS" : "English (South Sudan)",
                "en_SX" : "English (Sint Maarten)",
                "en_SZ" : "English (Swaziland)",
                "en_TC" : "English (Turks & Caicos Islands)",
                "en_TK" : "English (Tokelau)",
                "en_TO" : "English (Tonga)",
                "en_TT" : "English (Trinidad & Tobago)",
                "en_TV" : "English (Tuvalu)",
                "en_TZ" : "English (Tanzania)",
                "en_UG" : "English (Uganda)",
                "en_UM" : "English (U.S. Outlying Islands)",
                "en_US" : "English (United States)",
                "en_VC" : "English (St. Vincent & Grenadines)",
                "en_VG" : "English (British Virgin Islands)",
                "en_VI" : "English (U.S. Virgin Islands)",
                "en_VU" : "English (Vanuatu)",
                "en_WS" : "English (Samoa)",
                "en_ZA" : "English (South Africa)",
                "en_ZA" : "English (South Africa)",
                "en_ZM" : "English (Zambia)",
                "en_ZW" : "English (Zimbabwe)",
                "es_AR" : "Spanish (Argentina)",
                "es_BO" : "Spanish (Bolivia)",
                "es_BR" : "Spanish (Brazil)",
                "es_BZ" : "Spanish (Belize)",
                "es_CL" : "Spanish (Chile)",
                "es_CO" : "Spanish (Colombia)",
                "es_CR" : "Spanish (Costa Rica)",
                "es_CU" : "Spanish (Cuba)",
                "es_DO" : "Spanish (Dominican Republic)",
                "es_EA" : "Spanish (Ceuta & Melilla",
                "es_EC" : "Spanish (Ecuador)",
                "es_ES" : "Spanish (Spain)",
                "es_GQ" : "Spanish (Equatorial Guinea)",
                "es_GT" : "Spanish (Guatemala)",
                "es_HN" : "Spanish (Honduras)",
                "es_IC" : "Spanish (Canary Islands)",
                "es_MX" : "Spanish (Mexico)",
                "es_NI" : "Spanish (Nicaragua)",
                "es_PA" : "Spanish (Panama)",
                "es_PE" : "Spanish (Peru)",
                "es_PR" : "Spanish (Puerto Rico)",
                "es_PY" : "Spanish (Paraguay)",
                "es_SV" : "Spanish (El Salvador)",
                "es_US" : "Spanish (United States)",
                "es_UY" : "Spanish (Uruguay)",
                "es_VE" : "Spanish (Venezuela)",
                "et_EE" : "Estonian (Estonia)",
                "eu_ES" : "Basque (Spain)",
                "ewo_CM" : "Ewondo (Cameroon)",
                "fa_AF" : "Persian (Afghanistan)",
                "fa_IR" : "Persian (Iran)",
                "ff_CM" : "Fulah (Cameroon",
                "ps_AF" : "Pashto (Afghanistan)",
                "ff_GN" : "Fulah (Guinea)",
                "ff_MR" : "Fulah (Mauritania)",
                "ff_SN" : "Fulah (Senegal)",
                "fi_FI" : "Finnish (Finland)",
                "fil_PH" : "Filipino (Philippines)",
                "fo_DK" : "Faroese (Denmark)",
                "fo_FO" : "Faroese (Faroe Islands)",
                "fr_BE" : "French (Belgium)",
                "fr_BF" : "French (Burkina Faso)",
                "fr_BI" : "French (Burundi)",
                "fr_BJ" : "French (Benin)",
                "fr_BL" : "French (St. Barthélemy)",
                "fr_CA" : "French (Canada)",
                "fr_CD" : "French (Congo - Kinshasa)",
                "fr_CF" : "French (Central African Republic)",
                "fr_CG" : "French (Congo - Brazzaville)",
                "fr_CH" : "French (Switzerland)",
                "fr_CI" : "French (Côte d’Ivoire)",
                "fr_CM" : "French (Cameroon)",
                "fr_DJ" : "French (Djibouti)",
                "fr_DZ" : "French (Algeria)",
                "fr_FR" : "French (France)",
                "fr_GA" : "French (Gabon)",
                "fr_GF" : "French (French Guiana)",
                "fr_GN" : "French (Guinea)",
                "fr_GP" : "French (Guadeloupe)",
                "fr_GQ" : "French (Equatorial Guinea)",
                "fr_HT" : "French (Haiti)",
                "fr_KM" : "French (Comoros)",
                "fr_LU" : "French (Luxembourg)",
                "fr_MA" : "French (Morocco)",
                "fr_MC" : "French (Monaco)",
                "fr_MF" : "French (St. Martin)",
                "fr_MG" : "French (Madagascar)",
                "fr_ML" : "French (Mali)",
                "fr_MQ" : "French (Martinique)",
                "fr_MR" : "French (Mauritania)",
                "fr_MU" : "French (Mauritius)",
                "fr_NC" : "French (New Caledonia)",
                "fr_NE" : "French (Niger)",
                "fr_PF" : "French (French Polynesia)",
                "fr_PM" : "French (St. Pierre & Miquelon)",
                "fr_RE" : "French (Réunion)",
                "fr_RW" : "French (Rwanda)",
                "fr_SC" : "French (Seychelles)",
                "fr_SN" : "French (Senegal)",
                "fr_SY" : "French (Syria)",
                "fr_TD" : "French (Chad)",
                "fr_TG" : "French (Togo)",
                "fr_TN" : "French (Tunisia)",
                "fr_VU" : "French (Vanuatu)",
                "fr_WF" : "French (Wallis & Futuna)",
                "fr_YT" : "French (Mayotte)",
                "fur_IT" : "Friulian (Italy)",
                "fy_NL" : "Western Frisian (Netherlands)",
                "ga_IE" : "Irish (Ireland)",
                "ga_IE" : "Irish (Ireland)",
                "gd_GB" : "Scottish Gaelic (United Kingdom)",
                "gl_ES" : "Galician (Spain)",
                "gsw_CH" : "Swiss German (Switzerland)",
                "gsw_FR" : "Swiss German (France)",
                "gsw_LI" : "Swiss German (Liechtenstein)",
                "gu_IN" : "Gujarati (India)",
                "guz_KE" : "Gusii (Kenya)",
                "gv_IM" : "Manx (Isle of Man)",
                "ha_GH" : "Hausa (Ghana)",
                "ha_GH" : "Hausa (Ghana)",
                "ha_NE" : "Hausa (Niger)",
                "ha_NG" : "Hausa (Nigeria)",
                "haw_US" : "Hawaiian (United States)",
                "he_IL" : "Hebrew (Israel)",
                "hi_IN" : "Hindi (India)",
                "hr_BA" : "Croatian (Bosnia & Herzegovina)",
                "hr_HR" : "Croatian (Croatia)",
                "hsb" : "Upper Sorbian",
                "hsb_DE" : "Upper Sorbian (Germany)",
                "hu_HU" : "Hungarian (Hungary)",
                "hy_AM" : "Armenian (Armenia)",
                "ig_NG" : "Igbo (Nigeria)",
                "ii_CN" : "Sichuan Yi (China)",
                "id_ID" : "Indonesian (Indonesia)",
                "is_IS" : "Icelandic (Iceland)",
                "it_CH" : "Italian (Switzerland)",
                "it_IT" : "Italian (Italy)",
                "it_SM" : "Italian (San Marino)",
                "it_VA" : "Italian (Vatican City)",
                "iw_IL" : "Hebrew (Israel)",
                "ja_JP" : "Japanese (Japan)",
                "jgo_CM" : "Ngomba (Cameroon)",
                "jmc" : "Machame",
                "jmc_TZ" : "Machame (Tanzania)",
                "ka_GE" : "Georgian (Georgia)",
                "kab_DZ" : "Kabyle (Algeria)",
                "kam_KE" : "Kamba (Kenya)",
                "kde_TZ" : "Makonde (Tanzania)",
                "ml_IN" : "Malayalam (India)",
                "kea_CV" : "Kabuverdianu (Cape Verde)",
                "khq_ML" : "Koyra Chiini (Mali)",
                "ki_KE" : "Kikuyu (Kenya)",
                "kk_KZ" : "Kazakh (Kazakhstan)",
                "kkj_CM" : "Kako (Cameroon)",
                "kl_GL" : "Kalaallisut (Greenland)",
                "kln_KE" : "Kalenjin (Kenya)",
                "km_KH" : "Khmer (Cambodia)",
                "kn_IN" : "Kannada (India)",
                "ko_KP" : "Korean (North Korea)",
                "ko_KR" : "Korean (South Korea)",
                "kok_IN" : "Konkani (India)",
                "ks_IN" : "Kashmiri (India)",
                "ksb_TZ" : "Shambala (Tanzania)",
                "ksf_CM" : "Bafia (Cameroon)",
                "ksh_DE" : "Colognian (Germany)",
                "kw_GB" : "Cornish (United Kingdom)",
                "ky_KG" : "Kyrgyz (Kyrgyzstan)",
                "lag_TZ" : "Langi (Tanzania)",
                "lt_LT" : "Lithuanian (Lithuania)",
                "lb_LU" : "Luxembourgish (Luxembourg)",
                "lv_LV" : "Latvian (Latvia)",
                "lg_UG" : "Ganda (Uganda)",
                "mk_MK" : "Macedonian (Macedonia)",
                "ms_MY" : "Malay (Malaysia)",
                "mt_MT" : "Maltese (Malta)",
                "nl_BE" : "Dutch (Belgium)",
                "nl_NL" : "Dutch (Netherlands)",
                "no_NO" : "Norwegian (Norway)",
                "pl_PL" : "Polish (Poland)",
                "pt_AO" : "Portuguese (Angola)",
                "pt_BR" : "Portuguese (Brazil)",
                "pt_CH" : "Portuguese (Switzerland)",
                "pt_CV" : "Portuguese (Cape Verde)",
                "pt_GQ" : "Portuguese (Equatorial Guinea)",
                "pt_GW" : "Portuguese (Guinea-Bissau)",
                "pt_LU" : "Portuguese (Luxembourg)",
                "pt_MO" : "Portuguese (Macau SAR China)",
                "pt_MZ" : "Portuguese (Mozambique)",
                "pt_PT" : "Portuguese (Portugal)",
                "pt_ST" : "Portuguese (São Tomé & Príncipe)",
                "pt_TL" : "Portuguese (Timor-Leste)",
                "ro_RO" : "Romanian (Romania)",
                "ru_BY" : "Russian (Belarus)",
                "ru_KG" : "Russian (Kyrgyzstan)",
                "ru_KZ" : "Russian (Kazakhstan)",
                "ru_MD" : "Russian (Moldova)",
                "ru_RU" : "Russian (Russia)",
                "ru_UA" : "Russian (Ukraine)",
                "sk_SK" : "Slovak (Slovakia)",
                "prs_AF" : "Dari (Afghanistan)",
                "sl_SI" : "Slovenian (Slovenia)",
                "sq_AL" : "Albanian (Albania)",
                "sr_BA" : "Serbian (Bosnia and Herzegovina)",
                "sr_CS" : "Serbian (Serbia and Montenegro)",
                "sr_ME" : "Serbian (Montenegro)",
                "sq_ME" : "Albanian (Montenegro)",
                "sr_RS" : "Serbian (Serbia)",
                "sv_SE" : "Swedish (Sweden)",
                "ta_ID" : "Tamil (Indonesia)",
                "ta_IN" : "Tamil (India)",
                "ta_MY" : "Tamil (Malaysia)",
                "ta_MM" : "Tamil (Myanmar)",
                "ta_MU" : "Tamil (Mauritius)",
                "ta_PH" : "Tamil (Philippines)",
                "ta_SL" : "Tamil (Sierra Leone)",
                "ta_SG" : "Tamil (Singapore)",
                "ta_TH" : "Tamil (Thailand)",
                "th_TH" : "Thai (Thailand)",
                "th_TH_TH" : "Thai (Thailand)",
                "tr_TR" : "Turkish (Turkey)",
                "uk_UA" : "Ukrainian (Ukraine)",
                "vi_VN" : "Vietnamese (Vietnam)",
                "uz_UZ" : "Uzbek (Latin) (Uzbekistan)",
                "uz_UZ" : "Uzbek (Cyrillic) (Uzbekistan)",
                "uz_AF" : "Uzbek (Afghanistan)",
                "zu_ZA" : "Zulu (South Africa)",

        }

